[features]
seeds = false

[programs.devnet]
insurance_program = "4w2ksCnBSp2S4hSNUm1YZg8NzdTZ68mone4h6AkFirzQ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[test]
startup_wait = 15000
shutdown_wait = 5000

[idl]
out_dir = "target/idl"